/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Models.Product;
import Models.Register;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author mhd sathlan
 */
public class Cart extends javax.swing.JFrame {

    /**
     * Creates new form Cart
     */
    byte[] photo = null;
    String filename = null;

    public Cart() {
        initComponents();
    }

    public ArrayList<Product> ProductList() {
        ArrayList<Product> ProductList = new ArrayList<>();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/velo?serverTimezone=UTC", "root", "");
            String query = "Select * from Product";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            Product item;
            while (rs.next()) {
                item = new Product(rs.getInt("Id"), rs.getString("BName"), rs.getString("PName"), rs.getBytes("Image"), rs.getFloat("Price"), rs.getString("Size"));
                ProductList.add(item);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return ProductList;
    }

    public void show_Product() {
        ArrayList<Product> list = ProductList();
        DefaultTableModel model3 = (DefaultTableModel) jTableProdcuct.getModel();
        Object[] row = new Object[5];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getProductID();
            row[1] = list.get(i).getBrandName();
            row[2] = list.get(i).getProductName();
            row[3] = list.get(i).getPrice();
            row[4] = list.get(i).getSize();
            model3.addRow(row);
        }

    }

    public ArrayList<Register> RegisterList() {
        ArrayList<Register> RegisterList = new ArrayList<>();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/velo", "root", "");
            String query = "Select * from clogin";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            Register reg;
            while (rs.next()) {
                reg = new Register(rs.getString("Name"), rs.getString("NIC"), rs.getString("Address"), rs.getString("Email"), rs.getInt("Telephone"));
                RegisterList.add(reg);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return RegisterList;
    }

    public void show_Register() {
        ArrayList<Register> list = RegisterList();
        DefaultTableModel model3 = (DefaultTableModel) jTable2.getModel();
        Object[] row = new Object[5];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getName();
            row[1] = list.get(i).getNIC();
            row[2] = list.get(i).getAddress();
            row[3] = list.get(i).getEmail();
            row[4] = list.get(i).getTelephone();
            model3.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdcuct = new javax.swing.JTable();
        txtSearch1 = new javax.swing.JTextField();
        btnSearch1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lblImage = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        tblDetails = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 12, 104, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Product Id");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 11, -1, 23));

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_24px.png"))); // NOI18N
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 11, 50, 30));

        jTableProdcuct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Product Name", "Brand Name", "Price", "Size"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProdcuct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdcuctMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProdcuct);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 572, 105));

        txtSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearch1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 185, 104, -1));

        btnSearch1.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search_24px.png"))); // NOI18N
        btnSearch1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 184, 50, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Email");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 187, 62, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "NIC", "Email", "Telephone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 234, 572, 165));

        lblImage.setMaximumSize(new java.awt.Dimension(587, 405));
        lblImage.setMinimumSize(new java.awt.Dimension(587, 405));
        jPanel1.add(lblImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 227, 186));

        jLabel3.setText("Address");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, -1, -1));
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, 209, -1));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buy_64px.png"))); // NOI18N
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, 100, 70));

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_64px.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, 90, 70));
        jPanel1.add(tblDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 301, 290, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 971, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:   like '"+val+"%'"
        ArrayList<Product> al = new ArrayList<Product>();;
        //al = new ArrayList<AddItems>();
        String val = txtSearch.getText().toString();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/velo", "root", "");
            String query = "Select * from Product where Id like '" + val + "'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            Product Items;
            while (rs.next()) {
                Items = new Product(rs.getInt("Id"), rs.getString("BName"), rs.getString("PName"), rs.getBytes("Image"), rs.getFloat("Price"), rs.getString("Size"));
                al.add(Items);

            }
            DefaultTableModel model = (DefaultTableModel) jTableProdcuct.getModel();
            model.setRowCount(0);
            Object[] row = new Object[5];
            for (int i = 0; i < al.size(); i++) {
                row[0] = al.get(i).getProductID();
                row[1] = al.get(i).getBrandName();
                row[2] = al.get(i).getProductName();
                row[3] = al.get(i).getPrice();
                row[4] = al.get(i).getSize();
                model.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Cannot find Product Name", "Search Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jTableProdcuctMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdcuctMouseClicked
        // TODO add your handling code here:
        int i = jTableProdcuct.getSelectedRow();
        TableModel model = jTableProdcuct.getModel();
        // jLabel1.setText(model.getValueAt(i, 2).toString());
        byte[] img = (ProductList().get(i).getImage());
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lblImage.getWidth(), lblImage.getHeight(), Image.SCALE_SMOOTH));
        lblImage.setIcon(imageIcon);
    }//GEN-LAST:event_jTableProdcuctMouseClicked

    private void txtSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearch1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearch1ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        viewProduct reg = new viewProduct();
        reg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearch1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch1ActionPerformed
        // TODO add your handling code here:
        ArrayList<Register> al = new ArrayList<Register>();;
        //al = new ArrayList<AddItems>();
        String val = txtSearch1.getText().toString();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/velo", "root", "");
            String query = "Select * from clogin where Email like '" + val + "'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            Register reg;
            while (rs.next()) {
                reg = new Register(rs.getString("Name"), rs.getString("NIC"), rs.getString("Address"), rs.getString("Email"), rs.getInt("Telephone"));
                al.add(reg);
                // ad = new Register(rs.getString("Address"));

                txtAddress.setText(reg.getAddress().toString());

            }
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.setRowCount(0);
            Object[] row = new Object[4];
            for (int i = 0; i < al.size(); i++) {
                row[0] = al.get(i).getName();
                row[1] = al.get(i).getNIC();
                //row[2] = al.get(i).getAddress();
                row[2] = al.get(i).getEmail();
                row[3] = al.get(i).getTelephone();
                model.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Cannot find Email address", "Search Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSearch1ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        int YesORNo = JOptionPane.showConfirmDialog(null, "Do you want Buy", "Massage Option", JOptionPane.YES_NO_OPTION);
        if (YesORNo == 0) {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/velo", "root", "");
                //Statement st = con.createStatement();
                String query1 = "Insert into Buy (ProductId, ProductName, BrandName, Price, Size, Name, NIC, Address, Email, Telephone) VALUES (?,?,?,?,?,?,?,?,?,?)";
                PreparedStatement pst1 = con.prepareStatement(query1);

                int row = jTableProdcuct.getSelectedRow();
                int ProductId = (int) (jTableProdcuct.getModel().getValueAt(row, 0));
                pst1.setInt(1, ProductId);
                String ProductName = (jTableProdcuct.getModel().getValueAt(row, 1).toString());
                //txtId.getText();
                pst1.setString(2, ProductName);
                String BrandName = (jTableProdcuct.getModel().getValueAt(row, 2).toString());
                pst1.setString(3, BrandName);
                float Price = (float) (jTableProdcuct.getModel().getValueAt(row, 3));
                pst1.setFloat(4, Price);
                String Size = (jTableProdcuct.getModel().getValueAt(row, 4).toString());
                pst1.setString(5, Size);
                int row1 = jTable2.getSelectedRow();
                String Name = (jTable2.getModel().getValueAt(row1, 0).toString());
                pst1.setString(6, Name);
                String NIC = (jTable2.getModel().getValueAt(row1, 1).toString());
                pst1.setString(7, ProductName);
                //txtId.getText();
                pst1.setString(8, txtAddress.getText());
                String Email = (jTable2.getModel().getValueAt(row1, 2).toString());
                pst1.setString(9, Email);
                int Telephone = (int) (jTable2.getModel().getValueAt(row1, 3));
                pst1.setInt(10, Telephone);
                //String Size = (jTable2.getModel().getValueAt(row1, 4).toString());

                pst1.executeUpdate();
                JOptionPane.showMessageDialog(null, "Sucessfully Buied");
                /*viewProduct reg = new viewProduct();
                reg.setVisible(true);
                this.dispose();*/

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Sorry,Product is not avilable");
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/velo", "root", "");
                    //Statement st = con.createStatement();
                    String query1 = "Insert into Alert (ProductId, ProductName, BrandName, Price, Size) VALUES (?,?,?,?,?)";
                    PreparedStatement pst1 = con.prepareStatement(query1);
                    int row = jTableProdcuct.getSelectedRow();
                    int ProductId = (int) (jTableProdcuct.getModel().getValueAt(row, 0));
                    pst1.setInt(1, ProductId);
                    String ProductName = (jTableProdcuct.getModel().getValueAt(row, 1).toString());
                    //txtId.getText();
                    pst1.setString(2, ProductName);
                    String BrandName = (jTableProdcuct.getModel().getValueAt(row, 2).toString());
                    pst1.setString(3, BrandName);
                    float Price = (float) (jTableProdcuct.getModel().getValueAt(row, 3));
                    pst1.setFloat(4, Price);
                    String Size = (jTableProdcuct.getModel().getValueAt(row, 4).toString());
                    pst1.setString(5, Size);
                    pst1.executeUpdate();
                } catch (Exception e1) {
                    JOptionPane.showMessageDialog(null, e1);
                }
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSearch1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableProdcuct;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel tblDetails;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearch1;
    // End of variables declaration//GEN-END:variables
}
